export const COOKING_ASSISTANT = 'Cooking Assistant'
export const MY_EMAIL = 'info@gmail.com'
export const EMAIL = 'Email'
export const NAME = "Name"
export const MY_MOBILE_NUMBER = '+970599102215'
export const MOBILE_NUMBER = 'Mobile Number'
export const MESSAGE = 'Message'
export const HOME = 'Home'
export const ORDERS = 'Orders'
export const ABOUT = 'ABOUT'
export const CONTACT_US = 'CONTACT US'
export const FAQ= 'Faq'
export const SALE = 'Sale'
export const SAVE = 'Save'
export const SEND = 'Send'
export const ADD_TO_CART = 'Add to cart'
export const MY_CART = 'My cart'
export const SOCIAL_MEDIA_SECTION = 'Social media section'
export const PINTEREST = "Pinterest"
export const FACEBOOK = "Facebook"
export const INSTGRAM = 'Instgram'
export const THIS_FIELD_IS_REQUIRED = "This field is required"
export const CHECKOUT = "Checkout"
export const CHAT_WELCOME_MESSAGE = "Hi, i am your cooking assistant. Type the name of the dish you want to cook and let me handle finding the ingredients for you."
export const CHAT_TITLE = "Cooking Assistant"
export const IN_ACTIVE_CHAT_TITLE = "AI Cooking Assistant"
export const IN_ACTIVE_CHAT_SUB_TITLE = "Let me help you find the ingredients"
export const ALL_CATEGORIES = 'All categories'

